// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfskhiwlfkotvwxusuao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmc2toaXdsZmtvdHZ3eHVzdWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzM5NTMsImV4cCI6MjA2MTQ0OTk1M30.mGO2Nic8EmrNpzwiIn9mBdcKrQv5h8_s61hzEFtfXKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with session persistence
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    autoRefreshToken: true,
    debug: true
  }
});